name: Build Flatpak

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install Flatpak and flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Add Flathub remote in user context
        run: |
          flatpak --user remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          flatpak-builder --user --force-clean \
            --install-deps-from=flathub \
            build-dir your-app.yml

      - name: Export repository
        run: |
          flatpak build-export repo build-dir

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle \
            repo \
            your-app.flatpak \
            your.app.id \
            --runtime-repo=https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: your-app.flatpak
          path: your-app.flatpak
