name: Build Flatpak

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: PRE FLATPAKBUILDER DISK SPACE
        shell: bash
        run:   |
          echo "PRE AVAILABLE DISK SPACE:"
          df -h

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: palette.flatpak
          manifest-path: com.silverlan.PFM.yml
          cache-key: flatpak-builder-${{ github.sha }}

      #- name: Install Flatpak and flatpak-builder
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y flatpak flatpak-builder

      #- name: Add Flathub remote in user context
      #  run: |
      #    flatpak --user remote-add --if-not-exists flathub \
      #      https://dl.flathub.org/repo/flathub.flatpakrepo

      #- name: Build Flatpak
      #  run: |
      #    flatpak-builder --user --force-clean \
      #      --install-deps-from=flathub --repo=repo \
      #      build-dir com.silverlan.PFM.yml

      #- name: Export repository
      #  run: |
      #    flatpak build-export repo build-dir

      #- name: Create Flatpak bundle
      #  run: |
      #    flatpak build-bundle \
      #      repo \
      #      com.silverlan.PFM.flatpak \
      #      com.silverlan.PFM \
      #      --runtime-repo=https://dl.flathub.org/repo/flathub.flatpakrepo

      #- name: Upload Flatpak bundle
      #  uses: actions/upload-artifact@v4
      
      #  with:
      #    name: com.silverlan.PFM.flatpak
      #    path: com.silverlan.PFM.flatpak

      - name: Handle Error
        uses: Silverlan/common_actions/action_handle_error@main
        if: failure()
        
